<a href="https://colab.research.google.com/github/saminasultanmano-glitch/Machine-Learning-Models/blob/main/ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = pd.read_csv("/content/card_transdata.csv")
display(data)

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
0,57.877857,0.311140,1.945940,1.0,1.0,0.0,0.0,0.0
1,10.829943,0.175592,1.294219,1.0,0.0,0.0,0.0,0.0
2,5.091079,0.805153,0.427715,1.0,0.0,0.0,1.0,0.0
3,2.247564,5.600044,0.362663,1.0,1.0,0.0,1.0,0.0
4,44.190936,0.566486,2.222767,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
646084,34.145202,9.573078,0.684827,1.0,1.0,0.0,1.0,0.0
646085,6.328404,6.180955,0.365823,1.0,0.0,0.0,1.0,0.0
646086,12.979139,3.363080,1.061550,1.0,0.0,0.0,1.0,0.0
646087,20.309070,14.286222,6.543472,1.0,0.0,1.0,0.0,0.0
646088,22.345120,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.shape

(646089, 8)

In [ ]:
data.columns

Index(['distance_from_home', 'distance_from_last_transaction',
       'ratio_to_median_purchase_price', 'repeat_retailer', 'used_chip',
       'used_pin_number', 'online_order', 'fraud'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 646089 entries, 0 to 646088
Data columns (total 8 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   distance_from_home              646089 non-null  float64
 1   distance_from_last_transaction  646088 non-null  float64
 2   ratio_to_median_purchase_price  646088 non-null  float64
 3   repeat_retailer                 646088 non-null  float64
 4   used_chip                       646088 non-null  float64
 5   used_pin_number                 646088 non-null  float64
 6   online_order                    646088 non-null  float64
 7   fraud                           646088 non-null  float64
dtypes: float64(8)
memory usage: 39.4 MB

In [ ]:
data.describe()

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
count,646089.000000,646088.000000,646088.000000,646088.000000,646088.000000,646088.000000,646088.000000,646088.000000
mean,26.669310,5.033815,1.825763,0.881623,0.350370,0.101085,0.650921,0.087565
std,65.320884,26.915331,2.802047,0.323054,0.477086,0.301442,0.476679,0.282662
min,0.004874,0.000118,0.004399,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.879040,0.296006,0.475390,1.000000,0.000000,0.000000,0.000000,0.000000
50%,9.976900,0.997288,0.998656,1.000000,0.000000,0.000000,1.000000,0.000000
75%,25.794854,3.353243,2.101508,1.000000,1.000000,0.000000,1.000000,0.000000
max,10632.723672,11851.104565,267.802942,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
data.isnull().sum()

distance_from_home                0
distance_from_last_transaction    1
ratio_to_median_purchase_price    1
repeat_retailer                   1
used_chip                         1
used_pin_number                   1
online_order                      1
fraud                             1
dtype: int64

In [ ]:
data["distance_from_last_transaction"] = data["distance_from_last_transaction"].fillna(0)
data["ratio_to_median_purchase_price"] = data["ratio_to_median_purchase_price"].fillna(99)

In [ ]:
data.isnull().sum()

distance_from_home                0
distance_from_last_transaction    0
ratio_to_median_purchase_price    0
repeat_retailer                   1
used_chip                         1
used_pin_number                   1
online_order                      1
fraud                             1
dtype: int64

In [ ]:
data.describe()

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
count,646089.000000,646089.000000,646089.000000,646088.000000,646088.000000,646088.000000,646088.000000,646088.000000
mean,26.669310,5.033807,1.825914,0.881623,0.350370,0.101085,0.650921,0.087565
std,65.320884,26.915311,2.804651,0.323054,0.477086,0.301442,0.476679,0.282662
min,0.004874,0.000000,0.004399,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.879040,0.296005,0.475390,1.000000,0.000000,0.000000,0.000000,0.000000
50%,9.976900,0.997286,0.998658,1.000000,0.000000,0.000000,1.000000,0.000000
75%,25.794854,3.353236,2.101514,1.000000,1.000000,0.000000,1.000000,0.000000
max,10632.723672,11851.104565,267.802942,1.000000,1.000000,1.000000,1.000000,1.000000